### ISSUE TITLE
Trying to access resource allocation generates APPLICATION ERROR #2502 - Plugin page not found.

### ISSUE THREAD

**Issue by fmancardi** [vincentsels/ProjectManagement#10]
Mantis version: 1.2.11
Code has been modified as indicated on Mantis ISSUE 14329: Updating bug status should provide event to display mandatory plug-in fields

Login as administrator
Go to resource management and add a number for hours for administrator
Select Project X, Create an issue and assign to administrator
Selecte Project X (where exists at least ONE issue, and the issue is assigned to administrator) and click on Resource Allocation.
You got error message

Let me know if you need other kind of info to reproduce, like detail of other plugins installed

(Kudos! - this plugin rocks)

**Comment by vincentsels** [comment]
fmancardi, thanks for reporting. However, I can't seem to reproduce this. Do you still get this with the latest version ?

Could you help me out a bit ? If you change the following line in the Mantis core file plugin.php, around line 47:

``` php
if ( !is_file( $t_page ) ) {
        trigger_error( ERROR_PLUGIN_PAGE_NOT_FOUND, ERROR );
}
```

Into the following:

``` php
if ( !is_file( $t_page ) ) {
        trigger_error( $t_page, ERROR );
}
```

And let me know which page it's looking for, then I might learn a bit more. Might have been a teporary error which got fixed in a consecutive commit though.

**Comment by fmancardi** [comment]
Absolutely I will try to help you.
I will try as you suggested and try to provide feedback

regards

Francisco

On Tue, Jul 24, 2012 at 11:45 PM, Vincent Sels <
reply@reply.github.com

**Comment by vincentsels** [comment]
fmancardi, have you been able to try this ? Is this still an issue or can I close this ?

**Comment by fmancardi** [comment]
Unfortunately I've had no more time to explore this

I'm sorry
please close the issue
