### ISSUE TITLE
Upgrading the plugin schema failed in block #7

### ISSUE THREAD

**Issue by vincentsels** [vincentsels/ProjectManagement#11]
Hi,
I'm really interested in using your plugin for Mantis.
It should be fantastic plugin for us, because now our team is struggling with problems on project managing.

Unfortunately, during process of instalation, I've got that error:

APPLICATION ERROR #2503
Upgrading the plugin schema failed in block #7.

Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.

Do you know what is the solution? I'm using Mantis in version 1.2.10 and mssqlnative as a DB driver.
## 

Pozdrawiam
Daniel Sienkiewicz

**Comment by vincentsels** [comment]
Daniel,

I am unable to reproduce this error. Might be the "mssqlnative as a DB driver". Does that mean you're not using MySql as underlying database ?

The mentioned query block #7 contains the following code:

 array( 'CreateTableSQL', array( plugin_table( 'bug_customer' ), "
 bug_id
                    I NOTNULL UNSIGNED PRIMARY,
 type
                    I2 NOTNULL PRIMARY,
 customers
                    C(64) NOTNULL DEFAULT 0
 " ) ),

A possible cause I see is that I use the clause "NOTNULL DEFAULT 0", whereas I notice that elsewhere, for instance in the schema creation scripts of the original Mantis, they use all sorts of strange constructs, ie:

  type  I2 NOTNULL DEFAULT '0',
  possible_values 
                    C(255) NOTNULL DEFAULT \" '' \",
  default_value  C(255) NOTNULL DEFAULT \" '' \",
  valid_regexp  C(255) NOTNULL DEFAULT \" '' \",
  access_level_r  I2 NOTNULL DEFAULT '0',
  access_level_rw 
                    I2 NOTNULL DEFAULT '0',
  length_min   I  NOTNULL DEFAULT '0',
  length_max   I  NOTNULL DEFAULT '0',
  advanced  L NOTNULL DEFAULT \" '0' \",

I suppose that not all database engines can handle the syntax I'm using. I should look deeper into this though - I couldn't find a clear manual of how to use this syntax. Do you want me to look further into this or isn't it required anymore ?

**Comment by vincentsels** [comment]
Vincent,
yes, in fact I don't use MySQL database, but MS SQL 2008 R2.
I think there could be the problem - character field with default 0 - maybe it should be '0' instead?

I would be very appreciate if you could find the solution.

Daniel

**Comment by vincentsels** [comment]
Daniel,

Could you download the code from the "support-mssql" branch ? https://github.com/vincentsels/ProjectManagement/zipball/support-mssql

This adds a quote around the '0', as discussed. Perhaps this isn't enough, but it might just be this simple. I created a separate branch - if you would encounter other issues with your database, I can try to fix those too.

In order to manually remove any traces of this plugin, you need to take the following steps:
1. As you mentioned - first create a backup if this is a valuable database ;)
2. Log onto the database as a user with sufficient rights to drop tables in your mantis schema
3. Drop any tables that were already created during the installation of the plugin. These all begin with "mantis_plugin_projectmanagement_".
4. Execute the following sql statement: delete from mantis_config_table where config_id = 'plugin_ProjectManagement_schema'; -- not sure if anything will be there
5. Finally, execute the following sql statement: delete from mantis_plugin_table where basename = 'ProjectManagement'; -- also not sure if this will already exist

Next, copy the 'ProjectManagement' plugin subfolder from the zipfile to the plugins subfolder of your Mantis installation (remove the old directory if it was still there), and try to install it again!

Let me know if this worked, or if you still encounter any errors.

**Comment by dsienkiewicz** [comment]
Vincent,
unfortunately this fix still is not enough.

Now my error is at block #0:

APPLICATION ERROR #2503

Upgrading the plugin schema failed in block #0.

Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.

Maybe the problem is with all default values.
Im also not sure if column timestamp in table work or column function in table user_customer should be enclosed in some special characters - function for sure is reserved word in MS SQL.

**Comment by dsienkiewicz** [comment]
OK,
so the problem was with the function column. It should be specially treated, as it is reserved word in MS SQL.
I don't know how to achieve this in PHP, so I changed the name of this column in the script and then, after succesful installation, I changed back that name in database to function. 
I'm not sure if this is a good solution - I think there could be some issues with SELECT clause later.

But unfortunately, another problem is with query, when I enter the Project Management menu:
Error Code: 8120
Message: [Microsoft][SQL Server Native Client 10.0][SQL Server]Column 'mantis_bug_table.id' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
for clause SELECT b.id as bug_id, sum(w.minutes) as minutes, max(w.timestamp) as timestamp
FROM mantis_plugin_ProjectManagement_work_table w JOIN mantis_bug_table b ON w.bug_id = b.id
WHERE w.user_id = 2
AND w.book_date = 1343080800
AND w.minutes_type = 1
GROUP BY bug_id
ORDER BY timestamp DESC.

**Comment by vincentsels** [comment]
I'll rename the function column, and look at the problem with that query. Seems logical enough - some databases support grouping by column alias while others don't, I just have to change that to the actual column name. I'll search through the code if I use this elsewhere too.

**Comment by vincentsels** [comment]
I see you created issue #12 for this - thanks!

**Comment by vincentsels** [comment]
I'm considering this issue as closed - the problems with the creation of the scheme should be fixed now. Renamed column to function_description. Note that it isn't used yet - just wanted to already have it ready because I expect to use it in future functionality.
