### ISSUE TITLE
Mantis date format not respected

### ISSUE THREAD

**Issue by dregad** [vincentsels/ProjectManagement#2]
In the plugin, dates are displayed DD/MM/YYYY, instead of using the same formatting as defined in config_inc.php ('Y-m-d' in my case), e.g. in date entry fields and in registration overview page

**Comment by vincentsels** [comment]
I know... problem is that Mantis has trouble with the date format most commonly used in Belgium, DD/MM/YYYY, because php's strtotime interprets this incorrectly as MM/DD/YYYY. If you want support for DD/MM/YYYY in Mantis you need a 'hack'. There's (at least) one bug report for it in Mantis, http://www.mantisbt.org/bugs/view.php?id=13332, and I suggested a solution for it: https://github.com/mantisbt/mantisbt/pull/35
Until that's fixed & released (using my suggested solution or a better solution) I don't want to change this in my plugin, because I'd either have the same problem as in Mantis, or I'd have to add the same 'hack' which isn't really decent.

**Comment by vincentsels** [comment]
Should be fixed in latest master version. Would be great if anyone could test this and report any more issues!
