### ISSUE TITLE
Error message "APPLICATION WARNING #2400: Event "EVENT_BUG_STATUS_UPDATE_FORM" has not yet been declared."

### ISSUE THREAD

**Issue by blairsu** [vincentsels/ProjectManagement#7]
Dear Sir:
I download this plugin and install into my Mantisbt 1.2.8.
Then I found this error message keep showing on the screen.

When I google it, I found this open issue in mantisbt's issue tracking system.
http://www.mantisbt.org/bugs/view.php?id=14329

Should I just update the even_inc.php as your comment to avoid this error message first?

**Comment by vincentsels** [comment]
That's correct! In order to get the plugin to work, you'll need to add two lines in two files, as mentioned in the comments: events_inc.php and bug_change_status_page.php
I'm terribly sorry to have published the project in such a state that it doesn't work. I should at least mention it in the readme. Will update that asap.
Thanks for the interest in the plugin! If you encounter more issues, feel free to report them, either per mail or on the github project issues page.
Regards,
Vincent
